### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by hikettei** [hikettei/Caten#102]
- [x] September: Finish implementing GPT2 Inference w/ float32, clang.
  - [x] Solidify aIR System
    - [x] Make aIR type-safe
    - [x] Optimize AIR (FastGraph). Simplify GPT2 < 1.0s
    - [x] Eliminate bugs:
      - [x] Graphs that were needed are removed. (Static)
      - [x] Removed necessary nodes error (Dynamic) + Symbolic GPT2 Compilation
      - [x] Fix: `Model -> IR` Lowering. (replace call in `source/apis/initializer.lisp` w/ forward)
      - [x] Allow (forward module xxx nil)
      - [x] Loop Fusion (Nested) (e.g.: 4d matmul)
      - [x] Fix bugs in JIT: `optimizing matmul(x, y.T)` batched sdot_prod_attn wont work etc...
    - [x] Post-MultiExpr Optimization
    - [x] Prove the correctness of JIT kernels generated by Caten, by adding tests compared to PyTorch. (the more the better)
- [ ] October: Running GPT2 Inference on Metal, and vectorized/parallelized Clang.
  - [ ] Optimize: gemm
  - [ ] Implement: Hide Latency Optimization
  - [x] Implement: Index Computation Optimization
  - [ ] Implement: BEAM Search
  - [x] Fix: Vectorize Embedding
- [ ] November: Implement Quantization
  - [x] Complete caten/gguf
  - [ ] Implement LLaMA Inference
  - [x] O(n) time for the compilation (and with a little bugfix, LLAMA/GPT2 should work on Clang JIT)
- [x] December: Running CV Models or implementing training?
- [ ] Qwen2VL

**Comment by hikettei** [comment]
By February
```
-GPT2 Inference (maybe finishes 1~2 weeks)
- LLAMA3 Inference (not hard as long as gpt2 has worked)
- 4 or 8 bit quantization (gguf parser is already implemented, but dequantizer is not implemented)
- Backends: CLANG and METAL (if possible, CUDA)
```

**Comment by hikettei** [comment]
In December:
- [ ] GPT2 (MHA For Prepreq)
- [ ] ResNet50/YoLOv3 (ConvND=1Kernel)
- [ ] ViT
- [ ] AASM Inline
- [ ] AOT Shape Tracker
- [ ] Llama3 (AASM Inline, AOT Shape Tracker for prepreq)
