### ISSUE TITLE
TODO: BLAS generated by Caten (a.k.a: Symbolic and AOT Compilation)

### ISSUE THREAD

**Issue by hikettei** [hikettei/Caten#14]
- [ ] Symbolic BLAS and Math Library (like I did in cl-waffe2)
- [ ] AVM backend generated by our renderer (the equivalent to call-with-view in cl-waffe2)
- [ ] In-place mutation for the VM backend

**Comment by hikettei** [comment]
- [ ] Export_To_C: tensor.cみたいなの作ってTensor LibraryごとExportする？

**Comment by hikettei** [comment]
- [ ] Implementing caten/topi?
