### ISSUE TITLE
Optimize: O(N) Compilation Time in Transformer

### ISSUE THREAD

**Issue by hikettei** [hikettei/Caten#148]
- [ ] Currently iseq.lisp (or caten/apis) has a performance issue
- [ ] Compile Transformer > 70 Layers in 1s
- [ ] Support foreign kernel calling. (e.g.: Attention -> FlashAttention)

### Milestone

- [x] ~~Symbolic `!view` creation < 1e-4 sec~~
  - [x] optimizing fold-constant #178 
  - [x] ViewRange creates a cache for `from/to/by/size` in default #179 
  - [x] optimize %tensor->aasm
  - [x] Making symbolic `!view`  zero-cost
- [x] Benchmark baseline #179 
- [x] Revisit the algorithm in iseq.lisp
  - [x] Pattern Matcher should be O(N), not O(N^2).
    - [x] never running pattern matcher to the entire graph

**Comment by hikettei** [comment]
Before optimization: beautiful O(n^2) curve
![image](https://github.com/user-attachments/assets/3065b059-8338-4685-8388-d179ca6468f6)

**Comment by hikettei** [comment]
i'd like to devote December on implementing AutoScheduler/Metal Backend/Quantization, so implement gpt2 in this month

**Comment by hikettei** [comment]
- lower-all consists of 90% computation time
- (N=6) lower-all x 72 x forward_backward x {SIMPLIFIER_TIME_ON_ENTIRE_GRAPH}

**Comment by hikettei** [comment]
after merging #186 
![image](https://github.com/user-attachments/assets/60d690e7-3845-4ec6-9e92-d7485063902f)

**Comment by hikettei** [comment]
Completed for simplifier, but not for JIT
