### ISSUE TITLE
CI: TODO list for caten/benchmarks

### ISSUE THREAD

**Issue by hikettei** [hikettei/Caten#180]
- [x] GPT2 Compilation Time
- [ ] Gemm TFLOPS compared to OpenBLAS/Metal
- [ ] GPT2 Token/Second
