### ISSUE TITLE
Workload: Finally GPT2 Inference

### ISSUE THREAD

**Issue by hikettei** [hikettei/Caten#196]
## TODO
- [x] Optimize JIT, fix memory planner #193 
- [x] Complete test-suite/test-dynamic-shape.lisp
- [x] More tests on the JIT kernel accuracy (compared to PyTorch, like Multi Head Attention and scheduling for it. as far as I remember, mha in caten has a weird point in the view offsets) #210 
- [x] LayerNorm 
- [x] No duplicated computation for :ALLOC for the second `forward`
- [x] Build GPT2 from GGUF/PyTorch Weight
- [x] Make !view working for all the case
- [x] Make dynamic shape working for all the case

## Workload (finishes in 1~2 week, definitely by this month!)

- [x] #210 
  - [x] #212 
  - [x] #213 
  - [x] #216 
  - [x] #222 
    - [x] #219 
    - [x] #223 
    - [x] [todo: increase numerical stability for MultiHeadAttention where n_heads >= 8 #226 ]
    - [x] [todo: mha is unstable, fix for this, get test-multihead-attention working #245 ]
    - [x] [todo: shape tracker, permute+reshape in mha #245 ]
- [x] #211 
  - [x] #230 
- [x] #237 From GGUF, State Dict, BPE Tokenizer
- [x] Load and restore parameters from GGUF or PyTorch
- [x] Reimplement Scheduler (BFS) #251 
- [ ] GPT2 Inference (should) work.
- [ ] v0.3
- [ ] #192 (which would be a prepreq for more than 70 layers transformer)
- [ ] Add RoPE (by #215)
- [ ] Add TinyLlama/LLama3 8B Inference

**Comment by hikettei** [comment]
Caten/applications/gpt2

**Comment by hikettei** [comment]
- [ ] LayerNorm = 1 Kernels
- [ ] MultiHeadAttentions = Maybe 4~5 kernels, :shrink should be fused

**Comment by hikettei** [comment]
#228

**Comment by hikettei** [comment]
- [ ] Auto Scheduler, beat llama.cpp by the speed.
- [ ] Faster symbolic compilation
