### ISSUE TITLE
Enhancement: AOT Shape Tracker

### ISSUE THREAD

**Issue by hikettei** [hikettei/Caten#200]
- [ ] Add: (declaim-st ... (function name))
- [ ] C-c C-c and produce the shape error

**Comment by hikettei** [comment]
after the frontend is implemented and gpt2 has worked then it is time to think about the frontend API:
- [ ] AOT Shape Inference
- [ ] Beautiful API using macros
