### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by hikettei** [hikettei/Caten#348]
- **December 2024**
  - [x] GPT2
  - [x] ConvND=1 Kernel, Winograd
  - [x] Prerequisite for Polyhedral Compiler
  - [x] Solidify IRs #298 
  - [ ] O(n) dynamic schedule #231 
- **Janualy 2025**
  - [x] Start working on optimizing kernels by Auto Scheduler
    - [x] Loop Tiling, Array packing, Polyhedral Compiler
    - [x] Vectorized/Parallelized CLANG Backend
    - [x] CLANG AutoScheduler
    - [x] Metal GPU
    - [ ] WebGPU
    - [ ] CUDA
- **Febulary 2025**
  - [ ] ?
- **March 2025**
  - [ ] Stable Diffusion
  - [ ] Qwen2VL
  - [ ] LLama3
