### ISSUE TITLE
TODO: Complete `./source/common/documentation.lisp`

### ISSUE THREAD

**Issue by hikettei** [hikettei/Caten#95]
- [ ] Coding Rule (TODO: Write in EN)
  - [ ] 使用するノードは各ディレクトリのattrs.lispで宣言し，asdfのDependencyのTopにする
  - [ ] ドキュメントは各ディレクトリのdocumentation.lispに配置する
  - [ ] buildでdocgen
  - [ ] `(example s-expression)`でUsageを生成
  - [ ] `(jit-code xxx)`でJITされたコードを配置
  - [ ] (build-documentation)が呼び出されるまで中身は実行しない
- [x] 終わったらaIRの最適化

**Comment by hikettei** [comment]
### Profiling

```
(with-no-grad
  (caten (call (Transformer 64 8 1 1e-5 64) (make-tensor `(10 3)) (iconst 2))))
```
